# See the following link for all kotlin customization options
## https://openapi-generator.tech/docs/generators/kotlin
additionalProperties:
  packageName: com.florence.interfaces.client
  groupId: com.florence.clients
  artifactId: interfaces-service-client
  enumPropertyNaming: UPPERCASE
