# See the following link for all kotlin customization options
## https://openapi-generator.tech/docs/generators/kotlin
additionalProperties:
  packageName: com.florence.{{PLACEHOLDER}}.client
  groupId: com.florence.clients
  artifactId: {{PLACEHOLDER}}-service-client
  enumPropertyNaming: UPPERCASE
