name: Publish to AWS Code Artifact

# Whenever a branch gets merged to master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build and publish
        run: |
          export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain florence-pkg --domain-owner ${{ secrets.AWS_ADMIN_ACCOUNT_ID }} --query authorizationToken --output text`
          export CODEARTIFACT_URL=`aws codeartifact get-repository-endpoint --domain florence-pkg --domain-owner ${{ secrets.AWS_ADMIN_ACCOUNT_ID }} --repository florence-gradle --format maven --query repositoryEndpoint --output text`
          ./gradlew publish
